name: AsmodeusRPG
version: 0.0.1
main: sirlich.core.AsmodeusRPG
author: SirLich
description: RPG plugin testing
commands:
  spawn:
    description: Spawn in custom weapons
    usage: /spawn <material> <type> <level> <damage> <attack speed> <name> <Dura>