name: AsmodeusRPG
version: 0.0.2
main: sirlich.core.AsmodeusRPG
author: SirLich
description: RPG plugin testing
commands:
  spawn:
    description: Spawn in custom weapons
    usage: /spawn <material> <type> <level> <damage> <attack speed> <name> <Dura>
  spawnMob:
    description: Nothing here!
    usage: NOPE!
  toggle:
    desciption: Use to toggle all kinds of toggleable things
    usage: /toggle <toggleable item>
  inv:
    description: Open a blank 9 inventory
    usage: /inv
  create:
    description: Create a mob
    usage: /create